### ISSUE TITLE
tfhub model produces zero arrays

### ISSUE THREAD

**Issue by f-dx** [UKPLab/arxiv2018-xling-sentence-embeddings#2]
import nltk
import tensorflow_hub as hub
import tensorflow as tf
from nltk.tokenize import word_tokenize

class PmeanEncoder:
    
    def __init__(self):
        self.sess = None
        self.fetches = None
        self.embed = None
        
    def load(self):
        url_monolingual = 'https://public.ukp.informatik.tu-darmstadt.de/arxiv2018-xling-sentence-embeddings/tf-hub/monolingual/1'
        g = tf.Graph()
        with g.as_default():
            self.text_input = tf.placeholder(dtype=tf.string, shape=[None])
            self.embed = hub.Module(url_monolingual)
            self.fetches = self.embed(self.text_input)
            init_op = tf.group([tf.global_variables_initializer(), tf.tables_initializer()])
        g.finalize()
        config = tf.ConfigProto(device_count={'GPU': 7})
        self.sess = tf.Session(graph=g, config=config)
        self.sess.run(init_op)
    
    def run(self, text):
        data = word_tokenize(text)
        data = " ".join([s.lower() + "_en" for s in data])        
        embeddings_ = self.sess.run(self.fetches, feed_dict={self.text_input: [data]})
        return embeddings_
    
enc = PmeanEncoder()
enc.load()
enc.run("Hello World.")

And as an output I get 3600 zeros array. 
Will be grateful for the advice or recommendation.
Thanks.

**Comment by arueckle** [comment]
Only cross-lingual embeddings have the language suffixes "_en", "_de" etc.
For the monolingual embeddings, you should not append "_en".
