### ISSUE TITLE
Z norm

### ISSUE THREAD

**Issue by paulomann** [UKPLab/arxiv2018-xling-sentence-embeddings#3]
I'm currently confused where the Z norm is being calculated. I'm trying to replicate your method with my data, but I'm not sure how to make the Z norm. For example:

Given a matrix **emb** of size (5, 60), where we have 5 sentences, each being one row, and 60 dimensions, where the first 20 are from p-mean with p = 1, the ones emb[:, 20:40] with p = -inf and the rest being p = +inf. 

Where in this scenario/matrix, would I calculate the z norm?

**Comment by paulomann** [comment]
I have tested doing the z norm along the dim=1 and dim=0, and I got much better results from dim=1.

**Comment by arueckle** [comment]
This is the code we used:
```
m = np.mean(train_embeddings, axis=0)
s = np.std(train_embeddings, axis=0)
train_embeddings = (train_embeddings - m) / s
train_embeddings = train_embeddings / np.reshape(np.linalg.norm(train_embeddings, axis=1, ord=2), (train_embeddings.shape[0], 1))
test_embeddings = (test_embeddings - m) / s
test_embeddings = test_embeddings / np.reshape(np.linalg.norm(test_embeddings, axis=1, ord=2), (test_embeddings.shape[0], 1))
```

(Can be inserted here: https://github.com/facebookresearch/SentEval/blob/master/senteval/trec.py#L75)

**Comment by paulomann** [comment]
Thanks for your attention, @arueckle !
